// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAuthorFields {
  /** name */
  name: string;

  /** title */
  title: string;

  /** bio */
  bio: string;

  /** avatar */
  avatar?: Asset | undefined;

  /** Learn More Href */
  learnMoreHref?: string | undefined;

  /** email */
  email?: string | undefined;

  /** Social Links */
  socialLinks?: ISocialLink[] | undefined;
}

/** Content author */

export type IAuthor = Omit<Entry<any>, 'sys'> & {
  fields: IAuthorFields;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "author";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IBlogCategoryFields {
  /** name */
  name: string;

  /** slug */
  slug: string;

  /** order */
  order: number;
}

/** Category for a blog post */

export type IBlogCategory = Omit<Entry<any>, 'sys'> & {
  fields: IBlogCategoryFields;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blogCategory";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IBlogConfigurationFields {
  /** Hero Title */
  heroTitle: string;

  /** Hero Description */
  heroDescription: string;

  /** Featured Post */
  featuredPost: IBlogPost;
}

export type IBlogConfiguration = Omit<Entry<any>, 'sys'> & {
  fields: IBlogConfigurationFields;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blogConfiguration";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IBlogPostFields {
  /** Title */
  title: string;

  /** slug */
  slug: string;

  /** Excerpt */
  excerpt: string;

  /** Category */
  category: IBlogCategory;

  /** Featured Image */
  featuredImage: Asset;

  /** Thumbnail Image */
  thumbnailImage: Asset;

  /** Introduction */
  introduction?: Document | undefined;

  /** Sections */
  sections: IBlogPostSection[];

  /** Author */
  author: IAuthor;

  /** SEO Title */
  seoTitle?: string | undefined;

  /** SEO Description */
  seoDescription?: string | undefined;

  /** SEO Keywords */
  seoKeywords?: string[] | undefined;
}

export type IBlogPost = Omit<Entry<any>, 'sys'> & {
  fields: IBlogPostFields;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blogPost";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IBlogPostSectionFields {
  /** Title */
  title: string;

  /** slug */
  slug: string;

  /** Content Blocks */
  contentBlocks: (ICalloutBlock | IRichTextBlock | ITestimonialBlock)[];
}

export type IBlogPostSection = Omit<Entry<any>, 'sys'> & {
  fields: IBlogPostSectionFields;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blogPostSection";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICalloutBlockFields {
  /** title */
  title: string;

  /** content */
  content: Document;

  /** variant */
  variant: "lime" | "indigo" | "slate";
}

export type ICalloutBlock = Omit<Entry<any>, 'sys'> & {
  fields: ICalloutBlockFields;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "calloutBlock";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IRichTextBlockFields {
  /** title */
  title: string;

  /** content */
  content: Document;
}

/** Rich text content */

export type IRichTextBlock = Omit<Entry<any>, 'sys'> & {
  fields: IRichTextBlockFields;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "richTextBlock";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISocialLinkFields {
  /** title */
  title: string;

  /** platform */
  platform: "x" | "linkedin" | "facebook" | "instagram";

  /** url */
  url: string;
}

export type ISocialLink = Omit<Entry<any>, 'sys'> & {
  fields: ISocialLinkFields;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "socialLink";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITestimonialBlockFields {
  /** title */
  title: string;

  /** Quote Text */
  quoteText: string;

  /** Quote Attribution */
  quoteAttribution?: string | undefined;
}

/** Testimonial with attribution */

export type ITestimonialBlock = Omit<Entry<any>, 'sys'> & {
  fields: ITestimonialBlockFields;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "testimonialBlock";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "author"
  | "blogCategory"
  | "blogConfiguration"
  | "blogPost"
  | "blogPostSection"
  | "calloutBlock"
  | "richTextBlock"
  | "socialLink"
  | "testimonialBlock";

export type IEntry =
  | IAuthor
  | IBlogCategory
  | IBlogConfiguration
  | IBlogPost
  | IBlogPostSection
  | ICalloutBlock
  | IRichTextBlock
  | ISocialLink
  | ITestimonialBlock;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
